"""更新 frontend/lib/cost.ts 的 PRICING_TABLE。

使用方式:
    python scripts/update_pricing.py

來源:
    https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json

LiteLLM 是業界標準的 LLM gateway、cost map 涵蓋 1000+ models、活躍維護。
這個 script:
    1. 拉 LiteLLM raw JSON
    2. 對 WANTED_MATCHES 的每個 substring 做 lookup
    3. 找最 simple 的 native key(不要 bedrock/azure prefix 版)
    4. 把 USD per token 轉成 USD per 1M tokens
    5. 重新寫出整份 cost.ts(會覆蓋舊內容、保留 helper functions)

什麼時候跑這個 script:
    - provider 改 pricing(每季 / 半年)
    - 想新增 / 移除某個 model 的 substring
    - cost.ts 看起來過時、想 sync LiteLLM 最新
"""
from __future__ import annotations

import json
import sys
import urllib.request
from pathlib import Path

# Windows console 預設 cp1252、print 中文會炸；強制 stdout/stderr 用 UTF-8
try:
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
    sys.stderr.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
except Exception:
    pass

LITELLM_URL = "https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json"
COST_TS_PATH = Path(__file__).parent.parent / "frontend" / "lib" / "cost.ts"

# 我們的 frontend match key、順序重要(較具體放前面、避免短 prefix 攔截長的)
# 每筆要對 LiteLLM 內找 substring 匹配的 model key、提取 cost
WANTED_MATCHES: list[str] = [
    # Anthropic Claude(native key 通常就叫 'claude-X-Y')
    "claude-opus-4-7",
    "claude-opus-4-6",
    "claude-opus-4-5",
    "claude-opus-4",
    "claude-sonnet-4-6",
    "claude-sonnet-4-5",
    "claude-sonnet-4",
    "claude-haiku-4-5",
    "claude-haiku-4",
    "claude-3-5-sonnet",
    "claude-3-5-haiku",
    "claude-3-opus",

    # OpenAI
    "gpt-5",
    "gpt-4.1",
    "gpt-4o-mini",
    "gpt-4o",
    "gpt-4-turbo",
    "o3-mini",
    "o3",
    "o1-mini",
    "o1",

    # Google Gemini
    "gemini-3",
    "gemini-2.5-pro",
    "gemini-2.5-flash",
    "gemini-2.0-flash",
    "gemini-1.5-pro",
    "gemini-1.5-flash",

    # Groq LPU(快、便宜)
    "llama-4-scout",
    "llama-4-maverick",
    "llama-3.3-70b",
    "llama-3.1-405b",
    "llama-3.1-70b",
    "llama-3.1-8b",
    "deepseek-r1",
    "deepseek",
    "qwen-3",
    "qwen",
    "mixtral",
]

# LiteLLM 沒收的(免費 / 本地)、寫死
HARDCODED: dict[str, tuple[float, float, str]] = {
    "gemma":  (0.0, 0.0, "free tier (Google AI Studio gratis)"),
    "ollama": (0.0, 0.0, "local, no API cost"),
}


def fetch_litellm() -> dict:
    print(f"Fetching {LITELLM_URL} ...")
    req = urllib.request.Request(LITELLM_URL, headers={"User-Agent": "pipeline-orchestrator/update-pricing"})
    with urllib.request.urlopen(req, timeout=60) as r:
        raw = r.read().decode("utf-8")
    data = json.loads(raw)
    print(f"  loaded {len(data)} entries")
    return data


def find_pricing(litellm: dict, want: str) -> tuple[str, float, float] | None:
    """Find pricing for `want` substring in LiteLLM dict.

    優先級(由前到後):
      1. key 完全等於 want
      2. key 以 want 開頭(native 名稱)
      3. key contain want(provider prefix 變體, e.g. bedrock/anthropic.claude-...)

    回傳: (chosen_key, input_per_1M_USD, output_per_1M_USD)
    """
    want_lower = want.lower()
    exact: list[tuple[str, float, float]] = []
    starts: list[tuple[str, float, float]] = []
    contains: list[tuple[str, float, float]] = []

    for key, val in litellm.items():
        if not isinstance(val, dict):
            continue
        inp = val.get("input_cost_per_token")
        out = val.get("output_cost_per_token")
        if not isinstance(inp, (int, float)) or not isinstance(out, (int, float)):
            continue
        key_lower = key.lower()
        if key_lower == want_lower:
            exact.append((key, inp, out))
        elif key_lower.startswith(want_lower):
            starts.append((key, inp, out))
        elif want_lower in key_lower:
            contains.append((key, inp, out))

    pool = exact or starts or contains
    if not pool:
        return None

    # 在同 priority pool 內、選最短 key(避免 bedrock-prefixed / region-prefixed 變體)
    pool.sort(key=lambda x: (len(x[0]), x[0]))
    key, inp, out = pool[0]
    return key, inp * 1_000_000, out * 1_000_000


def generate_ts(rows: list[tuple[str, float, float, str]]) -> str:
    """rows: list of (substring, input_per_1M, output_per_1M, source_note)"""
    out = [
        "// LLM token 成本對照 (USD per 1M tokens)",
        "// AUTO-GENERATED by scripts/update_pricing.py — 不要手動改這個檔",
        "// Source: https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json",
        "// 重新生成: python scripts/update_pricing.py",
        "",
        "type Pricing = [match: string, inputPer1M: number, outputPer1M: number]",
        "",
        "// 順序重要：較具體放前面，避免短 prefix 攔截長 model name",
        "const PRICING_TABLE: Pricing[] = [",
    ]
    for sub, ip, op, src in rows:
        # 數值 round 到 6 位避免浮點 noise
        ip_s = f"{round(ip, 6):g}"
        op_s = f"{round(op, 6):g}"
        out.append(f"  ['{sub}', {ip_s}, {op_s}],  // {src}")
    out.extend([
        "]",
        "",
        "/** 算給定 model + token 用量的 USD 成本。配對不到 pricing 表回 null。 */",
        "export function computeCostUsd(model: string, inputTokens: number, outputTokens: number): number | null {",
        "  if (!model) return null",
        "  const lower = model.toLowerCase()",
        "  for (const [key, inP, outP] of PRICING_TABLE) {",
        "    if (lower.includes(key)) {",
        "      return (inputTokens * inP + outputTokens * outP) / 1_000_000",
        "    }",
        "  }",
        "  return null",
        "}",
        "",
        "/** 格式化 USD 金額：小金額用更精細小數、大金額用 2 位。null → 空字串。 */",
        "export function formatCostUsd(cost: number | null | undefined): string {",
        "  if (cost === null || cost === undefined) return ''",
        "  if (cost === 0) return '$0'",
        "  if (cost < 0.0001) return `$${cost.toExponential(1)}`",
        "  if (cost < 0.01)   return `$${cost.toFixed(4)}`",
        "  if (cost < 1)      return `$${cost.toFixed(3)}`",
        "  return `$${cost.toFixed(2)}`",
        "}",
        "",
    ])
    return "\n".join(out)


def main() -> int:
    try:
        litellm = fetch_litellm()
    except Exception as e:
        print(f"ERROR: 拉 LiteLLM JSON 失敗: {e}", file=sys.stderr)
        return 1

    rows: list[tuple[str, float, float, str]] = []
    misses: list[str] = []

    for sub in WANTED_MATCHES:
        if sub in HARDCODED:
            ip, op, note = HARDCODED[sub]
            rows.append((sub, ip, op, note))
            continue
        result = find_pricing(litellm, sub)
        if result:
            src_key, ip, op = result
            rows.append((sub, ip, op, f"src: {src_key}"))
        else:
            misses.append(sub)

    # 加 hardcoded 在最後(都是 0/0、放後面避免 'gemma' 攔截 'gemini')
    # 但這裡 WANTED_MATCHES 沒 include hardcoded、要主動加
    for sub, (ip, op, note) in HARDCODED.items():
        rows.append((sub, ip, op, note))

    # 寫檔
    ts = generate_ts(rows)
    COST_TS_PATH.write_text(ts, encoding="utf-8", newline="\n")

    print(f"\n=== Update 完成 ===")
    print(f"matched: {len(rows) - len(HARDCODED)} / {len(WANTED_MATCHES)} 個")
    if misses:
        print(f"misses (LiteLLM 沒收、可能 model 名稱不同): {misses}")
        print(f"  → cost.ts 內這些 substring 不會出現、frontend 對它們算 cost 回 null")
    print(f"hardcoded: {list(HARDCODED.keys())}")
    print(f"\nWrote: {COST_TS_PATH}")
    print(f"\n下一步: 在 :3005 hard reload (Ctrl+Shift+R) 看新 pricing 生效")

    return 0


if __name__ == "__main__":
    sys.exit(main())
