// LLM token 成本對照 (USD per 1M tokens)
// AUTO-GENERATED by scripts/update_pricing.py — 不要手動改這個檔
// Source: https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json
// 重新生成: python scripts/update_pricing.py

type Pricing = [match: string, inputPer1M: number, outputPer1M: number]

// 順序重要：較具體放前面，避免短 prefix 攔截長 model name
const PRICING_TABLE: Pricing[] = [
  ['claude-opus-4-7', 5, 25],  // src: claude-opus-4-7
  ['claude-opus-4-6', 5, 25],  // src: claude-opus-4-6
  ['claude-opus-4-5', 5, 25],  // src: claude-opus-4-5
  ['claude-opus-4', 15, 75],  // src: claude-opus-4-1
  ['claude-sonnet-4-6', 3, 15],  // src: claude-sonnet-4-6
  ['claude-sonnet-4-5', 3, 15],  // src: claude-sonnet-4-5
  ['claude-sonnet-4', 3, 15],  // src: claude-sonnet-4-5
  ['claude-haiku-4-5', 1, 5],  // src: claude-haiku-4-5
  ['claude-haiku-4', 1, 5],  // src: claude-haiku-4-5
  ['claude-3-5-sonnet', 3, 15],  // src: vertex_ai/claude-3-5-sonnet
  ['claude-3-5-haiku', 1, 5],  // src: vertex_ai/claude-3-5-haiku
  ['claude-3-opus', 15, 75],  // src: claude-3-opus-20240229
  ['gpt-5', 1.25, 10],  // src: gpt-5
  ['gpt-4.1', 2, 8],  // src: gpt-4.1
  ['gpt-4o-mini', 0.15, 0.6],  // src: gpt-4o-mini
  ['gpt-4o', 2.5, 10],  // src: gpt-4o
  ['gpt-4-turbo', 10, 30],  // src: gpt-4-turbo
  ['o3-mini', 1.1, 4.4],  // src: o3-mini
  ['o3', 2, 8],  // src: o3
  ['o1-mini', 1.21, 4.84],  // src: azure/o1-mini
  ['o1', 15, 60],  // src: o1
  ['gemini-3', 2, 12],  // src: gemini-3-pro-preview
  ['gemini-2.5-pro', 1.25, 10],  // src: gemini-2.5-pro
  ['gemini-2.5-flash', 0.3, 2.5],  // src: gemini-2.5-flash
  ['gemini-2.0-flash', 0.1, 0.4],  // src: gemini-2.0-flash
  ['gemini-1.5-flash', 0.075, 0],  // src: gemini/gemini-1.5-flash
  ['llama-4-scout', 0.1, 0.3],  // src: vercel_ai_gateway/meta/llama-4-scout
  ['llama-4-maverick', 0.50001, 1.50003],  // src: databricks/databricks-llama-4-maverick
  ['llama-3.3-70b', 0.85, 1.2],  // src: cerebras/llama-3.3-70b
  ['llama-3.1-405b', 10.68, 10.68],  // src: oci/meta.llama-3.1-405b-instruct
  ['llama-3.1-70b', 0.72, 0.72],  // src: oci/meta.llama-3.1-70b-instruct
  ['llama-3.1-8b', 0.03, 0.05],  // src: llamagate/llama-3.1-8b
  ['deepseek-r1', 1.35, 5.4],  // src: azure_ai/deepseek-r1
  ['deepseek', 0.28, 0.42],  // src: deepseek-chat
  ['qwen-3', 0.4, 0.8],  // src: cerebras/qwen-3-32b
  ['qwen', 0.15, 0.6],  // src: qwen.qwen3-32b-v1:0
  ['mixtral', 0.7, 0.7],  // src: mistral/open-mixtral-8x7b
  ['gemma', 0, 0],  // free tier (Google AI Studio gratis)
  ['ollama', 0, 0],  // local, no API cost
]

/** 後端 token_cost.py 算好的分項成本(單一真相來源)。
 *
 * 為什麼優先用後端的:Anthropic 的 input_tokens **不含**快取讀取,而快取讀取
 * 只要 input 的 1/10 價、快取寫入是 1.25~2 倍 —— 只拿 input+output 乘單價
 * (即下面的 computeCostUsd)會算錯好幾倍。後端才拿得到完整的四種 token。
 */
export type BackendCost = {
  priced: boolean
  partial?: boolean
  model_key?: string
  input_usd: number
  cache_read_usd: number
  cache_write_usd: number
  output_usd: number
  total_usd: number
  saved_usd: number
  prompt_tokens: number
  total_tokens: number
  note?: string
  pricing_as_of?: string
}

/** 取後端成本;沒有(舊 run / 後端沒模組)才回 null 讓呼叫端走 fallback。 */
export function backendCostUsd(cost: BackendCost | null | undefined): number | null {
  if (!cost || !cost.priced) return null
  return cost.total_usd
}

/** 算給定 model + token 用量的 USD 成本。配對不到 pricing 表回 null。
 *  ⚠️ 只涵蓋 input/output、**不含快取**,僅在後端沒給 cost 時當退路。 */
/** 算給定 model + token 用量的 USD 成本。配對不到 pricing 表回 null。
 *  ⚠️ 只涵蓋 input/output、**不含快取**,僅在後端沒給 cost 時當退路。 */
export function computeCostUsd(model: string, inputTokens: number, outputTokens: number): number | null {
  if (!model) return null
  const lower = model.toLowerCase()
  for (const [key, inP, outP] of PRICING_TABLE) {
    if (lower.includes(key)) {
      return (inputTokens * inP + outputTokens * outP) / 1_000_000
    }
  }
  return null
}

/** 格式化 USD 金額：小金額用更精細小數、大金額用 2 位。null → 空字串。 */
export function formatCostUsd(cost: number | null | undefined): string {
  if (cost === null || cost === undefined) return ''
  if (cost === 0) return '$0'
  if (cost < 0.0001) return `$${cost.toExponential(1)}`
  if (cost < 0.01)   return `$${cost.toFixed(4)}`
  if (cost < 1)      return `$${cost.toFixed(3)}`
  return `$${cost.toFixed(2)}`
}
